CREATE DATABASE IF NOT EXISTS HACKATHON_DB;
USE DATABASE HACKATHON_DB;
CREATE SCHEMA IF NOT EXISTS HACKATHON_DM;
USE SCHEMA HACKATHON_DM;

//DIM_REGION 만들기
CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    REGION_NAME VARCHAR(100) NOT NULL,
    SPH_PROVINCE_CODE VARCHAR(10),
    SPH_CITY_CODE VARCHAR(10),
    RICHGO_SD VARCHAR(50),
    RICHGO_SGG VARCHAR(50),
    AJD_INSTALL_STATE VARCHAR(50),
    AJD_INSTALL_CITY VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REGION_ID)
);

INSERT INTO DIM_REGION (
    REGION_NAME,
    SPH_PROVINCE_CODE,
    SPH_CITY_CODE,
    RICHGO_SD,
    RICHGO_SGG,
    AJD_INSTALL_STATE,
    AJD_INSTALL_CITY
)
VALUES
('중구', '11', '11140', '서울', '중구', '서울', '중구'),
('영등포구', '11', '11560', '서울', '영등포구', '서울', '영등포구'),
('서초구', '11', '11650', '서울', '서초구', '서울', '서초구');

SELECT *
FROM DIM_REGION
ORDER BY REGION_ID;


//STG_CARD_SALES 만들기
CREATE OR REPLACE TABLE STG_CARD_SALES AS
SELECT
    PROVINCE_CODE,
    CITY_CODE,
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH AS YEAR_MONTH,
    GENDER,
    AGE_GROUP,
    LIFESTYLE,
    TOTAL_SALES,
    TOTAL_COUNT,
    FOOD_SALES,
    HOME_LIFE_SERVICE_SALES,
    EDUCATION_ACADEMY_SALES,
    ELECTRONICS_FURNITURE_SALES,
    LARGE_DISCOUNT_STORE_SALES,
    SMALL_RETAIL_STORE_SALES,
    E_COMMERCE_SALES
FROM SPH_POPULATION_CONSUMPTION_DATA.GRANDATA.CARD_SALES_INFO
WHERE CITY_CODE IN ('11140', '11560', '11650');

//행수 확인
SELECT COUNT(*) AS ROW_COUNT
FROM STG_CARD_SALES;

//상위10개
SELECT *
FROM STG_CARD_SALES
LIMIT 10;

//월형식확인
SELECT DISTINCT YEAR_MONTH
FROM STG_CARD_SALES
ORDER BY YEAR_MONTH
LIMIT 20;

//지역코드확인
SELECT DISTINCT CITY_CODE
FROM STG_CARD_SALES
ORDER BY CITY_CODE;

//STG_ASSET_INCOME 만들기
CREATE OR REPLACE TABLE STG_ASSET_INCOME AS
SELECT
    PROVINCE_CODE,
    CITY_CODE,
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH AS YEAR_MONTH,
    INCOME_TYPE,
    GENDER,
    AGE_GROUP,
    CUSTOMER_COUNT,
    AVERAGE_INCOME,
    AVERAGE_HOUSEHOLD_INCOME,
    MEDIAN_INCOME,
    AVERAGE_ASSET_AMOUNT,
    RATE_HIGHEND,
    OWN_HOUSING_COUNT,
    MULTIPLE_HOUSING_COUNT
FROM SPH_POPULATION_CONSUMPTION_DATA.GRANDATA.ASSET_INCOME_INFO
WHERE CITY_CODE IN ('11140', '11560', '11650');

//행수확인
SELECT COUNT(*) AS ROW_COUNT
FROM STG_ASSET_INCOME;

//상위10개확인
SELECT *
FROM STG_ASSET_INCOME
LIMIT 10;

//월형식확인
SELECT DISTINCT YEAR_MONTH
FROM STG_ASSET_INCOME
ORDER BY YEAR_MONTH
LIMIT 20;

//지역코드확인
SELECT DISTINCT CITY_CODE
FROM STG_ASSET_INCOME
ORDER BY CITY_CODE;

//STG_APT_PRICE 만들기
CREATE OR REPLACE TABLE STG_APT_PRICE AS
SELECT
    BJD_CODE,
    SD,
    SGG,
    EMD,
    REPLACE(SUBSTR(YYYYMMDD, 1, 7), '-', '') AS YEAR_MONTH,
    TOTAL_HOUSEHOLDS,
    MEME_PRICE_PER_SUPPLY_PYEONG,
    JEONSE_PRICE_PER_SUPPLY_PYEONG
FROM RICHGO_POPULATION_APARTMENT_DATA.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD = '서울'
  AND SGG IN ('중구', '영등포구', '서초구');

//행 수 확인
SELECT COUNT(*) AS ROW_COUNT
FROM STG_APT_PRICE;

//상위 10개 확인
SELECT *
FROM STG_APT_PRICE
LIMIT 10;

//월 형식 확인
SELECT DISTINCT YEAR_MONTH
FROM STG_APT_PRICE
ORDER BY YEAR_MONTH
LIMIT 20;

//지역 확인
SELECT DISTINCT SD, SGG
FROM STG_APT_PRICE
ORDER BY SD, SGG;

//가격 컬럼 null 여부 간단 확인
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(MEME_PRICE_PER_SUPPLY_PYEONG) AS MEME_NOT_NULL,
    COUNT(JEONSE_PRICE_PER_SUPPLY_PYEONG) AS JEONSE_NOT_NULL
FROM STG_APT_PRICE;

//STG_FAMILY_PROFILE 만들기
CREATE OR REPLACE TABLE STG_FAMILY_PROFILE AS
SELECT
    BJD_CODE,
    SD,
    SGG,
    EMD,
    REPLACE(SUBSTR(YYYYMMDD, 1, 7), '-', '') AS YEAR_MONTH,
    AGE_UNDER5,
    FEMALE_20TO40,
    AGE_UNDER5_PER_FEMALE_20TO40
FROM RICHGO_POPULATION_APARTMENT_DATA.HACKATHON_2025Q2.REGION_MOIS_POPULATION_AGE_UNDER5_PER_FEMALE_20TO40_M_H
WHERE SD = '서울'
  AND SGG IN ('중구', '영등포구', '서초구');

//row 수 확인
SELECT COUNT(*) AS ROW_COUNT
FROM STG_FAMILY_PROFILE;

//상위 10개 보기
SELECT *
FROM STG_FAMILY_PROFILE
LIMIT 10;

//월 형식 확인
SELECT DISTINCT YEAR_MONTH
FROM STG_FAMILY_PROFILE
ORDER BY YEAR_MONTH
LIMIT 20;

//지역 확인
SELECT DISTINCT SD, SGG
FROM STG_FAMILY_PROFILE
ORDER BY 1, 2;

//STG_RENTAL_TREND 만들기
CREATE OR REPLACE TABLE STG_RENTAL_TREND AS
SELECT
    REPLACE(SUBSTR(TO_VARCHAR(YEAR_MONTH), 1, 7), '-', '') AS YEAR_MONTH,
    INSTALL_STATE,
    RENTAL_MAIN_CATEGORY,
    RENTAL_SUB_CATEGORY,
    CONTRACT_COUNT,
    OPEN_COUNT,
    PAYEND_COUNT,
    OPEN_CVR,
    PAYEND_CVR,
    AVG_NET_SALES,
    AVG_POLICY_AMOUNT
FROM AJD_SUBSCRIPTION_CONTRACT_DATA.TELECOM_INSIGHTS.V06_RENTAL_CATEGORY_TRENDS
WHERE INSTALL_STATE = '서울';

//row 수 확인
SELECT COUNT(*) AS ROW_COUNT
FROM STG_RENTAL_TREND;

//상위 10개 확인
SELECT *
FROM STG_RENTAL_TREND
LIMIT 10;

//월 형식 확인
SELECT DISTINCT YEAR_MONTH
FROM STG_RENTAL_TREND
ORDER BY YEAR_MONTH
LIMIT 20;

//지역 확인
SELECT DISTINCT INSTALL_STATE
FROM STG_RENTAL_TREND
ORDER BY INSTALL_STATE;

//AGG_CARD_SALES_REGION_MONTH 카드소비 구/월 기준 집계
CREATE OR REPLACE TABLE AGG_CARD_SALES_REGION_MONTH AS
SELECT
    CITY_CODE,
    YEAR_MONTH,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(TOTAL_COUNT) AS TOTAL_COUNT,
    SUM(FOOD_SALES) AS FOOD_SALES,
    SUM(HOME_LIFE_SERVICE_SALES) AS HOME_LIFE_SERVICE_SALES,
    SUM(EDUCATION_ACADEMY_SALES) AS EDUCATION_ACADEMY_SALES,
    SUM(ELECTRONICS_FURNITURE_SALES) AS ELECTRONICS_FURNITURE_SALES,
    SUM(LARGE_DISCOUNT_STORE_SALES) AS LARGE_DISCOUNT_STORE_SALES,
    SUM(SMALL_RETAIL_STORE_SALES) AS SMALL_RETAIL_STORE_SALES,
    SUM(E_COMMERCE_SALES) AS E_COMMERCE_SALES
FROM STG_CARD_SALES
GROUP BY CITY_CODE, YEAR_MONTH;

//row 수
SELECT COUNT(*) AS ROW_COUNT
FROM AGG_CARD_SALES_REGION_MONTH;

//상위 10개
SELECT *
FROM AGG_CARD_SALES_REGION_MONTH
ORDER BY CITY_CODE, YEAR_MONTH
LIMIT 10;

//지역 개수 확인
SELECT DISTINCT CITY_CODE
FROM AGG_CARD_SALES_REGION_MONTH
ORDER BY CITY_CODE;

//월 개수 확인
SELECT MIN(YEAR_MONTH) AS MIN_YM, MAX(YEAR_MONTH) AS MAX_YM
FROM AGG_CARD_SALES_REGION_MONTH;

//AGG_ASSET_INCOME_REGION_MONTH 만들기
CREATE OR REPLACE TABLE AGG_ASSET_INCOME_REGION_MONTH AS
SELECT
    CITY_CODE,
    YEAR_MONTH,
    SUM(CUSTOMER_COUNT) AS CUSTOMER_COUNT,
    AVG(AVERAGE_INCOME) AS AVG_INCOME,
    AVG(AVERAGE_HOUSEHOLD_INCOME) AS AVG_HOUSEHOLD_INCOME,
    AVG(MEDIAN_INCOME) AS MEDIAN_INCOME,
    AVG(AVERAGE_ASSET_AMOUNT) AS AVG_ASSET_AMOUNT,
    AVG(RATE_HIGHEND) AS RATE_HIGHEND,
    SUM(OWN_HOUSING_COUNT) AS OWN_HOUSING_COUNT,
    SUM(MULTIPLE_HOUSING_COUNT) AS MULTIPLE_HOUSING_COUNT
FROM STG_ASSET_INCOME
GROUP BY CITY_CODE, YEAR_MONTH;

//row 수
SELECT COUNT(*) AS ROW_COUNT
FROM AGG_ASSET_INCOME_REGION_MONTH;

//상위 10개
SELECT *
FROM AGG_ASSET_INCOME_REGION_MONTH
ORDER BY CITY_CODE, YEAR_MONTH
LIMIT 10;

//지역 코드 확인
SELECT DISTINCT CITY_CODE
FROM AGG_ASSET_INCOME_REGION_MONTH
ORDER BY CITY_CODE;

//월 범위 확인
SELECT MIN(YEAR_MONTH) AS MIN_YM, MAX(YEAR_MONTH) AS MAX_YM
FROM AGG_ASSET_INCOME_REGION_MONTH;

//AGG_APT_PRICE_REGION_MONTH 만들기
CREATE OR REPLACE TABLE AGG_APT_PRICE_REGION_MONTH AS
SELECT
    SGG,
    YEAR_MONTH,
    SUM(TOTAL_HOUSEHOLDS) AS TOTAL_HOUSEHOLDS,
    AVG(MEME_PRICE_PER_SUPPLY_PYEONG) AS AVG_MEME_PRICE_PER_SUPPLY_PYEONG,
    AVG(JEONSE_PRICE_PER_SUPPLY_PYEONG) AS AVG_JEONSE_PRICE_PER_SUPPLY_PYEONG
FROM STG_APT_PRICE
GROUP BY SGG, YEAR_MONTH;

//row 수
SELECT COUNT(*) AS ROW_COUNT
FROM AGG_APT_PRICE_REGION_MONTH;

//상위 10개
SELECT *
FROM AGG_APT_PRICE_REGION_MONTH
ORDER BY SGG, YEAR_MONTH
LIMIT 10;

//지역 확인
SELECT DISTINCT SGG
FROM AGG_APT_PRICE_REGION_MONTH
ORDER BY SGG;

//월 범위 확인
SELECT MIN(YEAR_MONTH) AS MIN_YM, MAX(YEAR_MONTH) AS MAX_YM
FROM AGG_APT_PRICE_REGION_MONTH;

//AGG_FAMILY_PROFILE_REGION_MONTH 만들기
CREATE OR REPLACE TABLE AGG_FAMILY_PROFILE_REGION_MONTH AS
SELECT
    SGG,
    YEAR_MONTH,
    SUM(AGE_UNDER5) AS AGE_UNDER5,
    SUM(FEMALE_20TO40) AS FEMALE_20TO40,
    SUM(AGE_UNDER5) / NULLIF(SUM(FEMALE_20TO40), 0) AS AGE_UNDER5_PER_FEMALE_20TO40
FROM STG_FAMILY_PROFILE
GROUP BY SGG, YEAR_MONTH;

//row 수
SELECT COUNT(*) AS ROW_COUNT
FROM AGG_FAMILY_PROFILE_REGION_MONTH;

//상위 10개
SELECT *
FROM AGG_FAMILY_PROFILE_REGION_MONTH
ORDER BY SGG, YEAR_MONTH
LIMIT 10;

//지역 확인
SELECT DISTINCT SGG
FROM AGG_FAMILY_PROFILE_REGION_MONTH
ORDER BY SGG;

//월 범위 확인
SELECT MIN(YEAR_MONTH) AS MIN_YM, MAX(YEAR_MONTH) AS MAX_YM
FROM AGG_FAMILY_PROFILE_REGION_MONTH;

//FACT_REGION_MONTH_PROFILE 만들기
CREATE OR REPLACE TABLE FACT_REGION_MONTH_PROFILE AS
SELECT
    R.REGION_ID,
    R.REGION_NAME,
    C.YEAR_MONTH,
    C.TOTAL_SALES,
    C.TOTAL_COUNT,
    C.FOOD_SALES,
    C.HOME_LIFE_SERVICE_SALES,
    C.EDUCATION_ACADEMY_SALES,
    C.ELECTRONICS_FURNITURE_SALES,
    C.LARGE_DISCOUNT_STORE_SALES,
    C.SMALL_RETAIL_STORE_SALES,
    C.E_COMMERCE_SALES,
    A.CUSTOMER_COUNT,
    A.AVG_INCOME,
    A.AVG_HOUSEHOLD_INCOME,
    A.MEDIAN_INCOME,
    A.AVG_ASSET_AMOUNT,
    A.RATE_HIGHEND,
    A.OWN_HOUSING_COUNT,
    A.MULTIPLE_HOUSING_COUNT,
    P.TOTAL_HOUSEHOLDS,
    P.AVG_MEME_PRICE_PER_SUPPLY_PYEONG,
    P.AVG_JEONSE_PRICE_PER_SUPPLY_PYEONG,
    F.AGE_UNDER5,
    F.FEMALE_20TO40,
    F.AGE_UNDER5_PER_FEMALE_20TO40
FROM DIM_REGION R
JOIN AGG_CARD_SALES_REGION_MONTH C
    ON R.SPH_CITY_CODE = C.CITY_CODE
LEFT JOIN AGG_ASSET_INCOME_REGION_MONTH A
    ON R.SPH_CITY_CODE = A.CITY_CODE
   AND C.YEAR_MONTH = A.YEAR_MONTH
LEFT JOIN AGG_APT_PRICE_REGION_MONTH P
    ON R.RICHGO_SGG = P.SGG
   AND C.YEAR_MONTH = P.YEAR_MONTH
LEFT JOIN AGG_FAMILY_PROFILE_REGION_MONTH F
    ON R.RICHGO_SGG = F.SGG
   AND C.YEAR_MONTH = F.YEAR_MONTH;

//확인
SELECT COUNT(*) AS ROW_COUNT
FROM FACT_REGION_MONTH_PROFILE;

SELECT *
FROM FACT_REGION_MONTH_PROFILE
ORDER BY REGION_ID, YEAR_MONTH
LIMIT 20;

//FACT_RENTAL_MARKET_TREND 만들기
CREATE OR REPLACE TABLE FACT_RENTAL_MARKET_TREND AS
SELECT
    R.REGION_ID,
    R.REGION_NAME,
    T.YEAR_MONTH,
    T.RENTAL_MAIN_CATEGORY,
    T.RENTAL_SUB_CATEGORY,
    T.CONTRACT_COUNT,
    T.OPEN_COUNT,
    T.PAYEND_COUNT,
    T.OPEN_CVR,
    T.PAYEND_CVR,
    T.AVG_NET_SALES,
    T.AVG_POLICY_AMOUNT
FROM DIM_REGION R
JOIN STG_RENTAL_TREND T
    ON R.AJD_INSTALL_STATE = T.INSTALL_STATE;

//확인
SELECT COUNT(*) AS ROW_COUNT
FROM FACT_RENTAL_MARKET_TREND;

SELECT *
FROM FACT_RENTAL_MARKET_TREND
ORDER BY REGION_ID, YEAR_MONTH
LIMIT 20;

//가구유형 분류 표
CREATE OR REPLACE VIEW VW_REGION_HOUSEHOLD_SEGMENT AS
SELECT
    REGION_ID,
    REGION_NAME,
    YEAR_MONTH,
    AVG_INCOME,
    AVG_HOUSEHOLD_INCOME,
    AVG_ASSET_AMOUNT,
    RATE_HIGHEND,
    AVG_MEME_PRICE_PER_SUPPLY_PYEONG,
    AVG_JEONSE_PRICE_PER_SUPPLY_PYEONG,
    AGE_UNDER5,
    FEMALE_20TO40,
    AGE_UNDER5_PER_FEMALE_20TO40,
    CASE
        WHEN AGE_UNDER5_PER_FEMALE_20TO40 >= 0.15 THEN '육아가구'
        WHEN AVG_HOUSEHOLD_INCOME >= 80000 AND AVG_MEME_PRICE_PER_SUPPLY_PYEONG >= 3000 THEN '프리미엄가구'
        WHEN AVG_HOUSEHOLD_INCOME < 50000 THEN '가성비가구'
        ELSE '일반가구'
    END AS HOUSEHOLD_SEGMENT,
    CASE
        WHEN AVG_HOUSEHOLD_INCOME >= 80000 THEN 'PREMIUM'
        WHEN AVG_HOUSEHOLD_INCOME >= 50000 THEN 'MID'
        ELSE 'BASIC'
    END AS BUDGET_TIER
FROM FACT_REGION_MONTH_PROFILE;

//확인
SELECT *
FROM VW_REGION_HOUSEHOLD_SEGMENT
ORDER BY REGION_ID, YEAR_MONTH
LIMIT 20;

//체크리스트 룰 테이블
CREATE OR REPLACE TABLE DIM_CHECKLIST_RULE (
    RULE_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    HOUSEHOLD_SEGMENT VARCHAR(50),
    BUDGET_TIER VARCHAR(20),
    ITEM_NAME VARCHAR(200),
    PRIORITY NUMBER,
    IS_RENTAL_RELATED BOOLEAN,
    ITEM_CATEGORY VARCHAR(100)
);

//임시 분류 데이터 삽입
INSERT INTO DIM_CHECKLIST_RULE
    (HOUSEHOLD_SEGMENT, BUDGET_TIER, ITEM_NAME, PRIORITY, IS_RENTAL_RELATED, ITEM_CATEGORY)
VALUES
    ('육아가구', 'BASIC', '정수기 렌탈 검토', 1, TRUE, '가전'),
    ('육아가구', 'MID', '공기청정기 렌탈 검토', 2, TRUE, '가전'),
    ('육아가구', 'PREMIUM', '세탁기/건조기 렌탈 검토', 3, TRUE, '가전'),
    ('프리미엄가구', 'PREMIUM', '냉장고 프리미엄 렌탈 검토', 1, TRUE, '가전'),
    ('프리미엄가구', 'PREMIUM', '침대/매트리스 렌탈 검토', 2, TRUE, '가구'),
    ('가성비가구', 'BASIC', '인터넷/이사 필수비용 우선 점검', 1, FALSE, '생활'),
    ('가성비가구', 'BASIC', '가성비 정수기 렌탈 검토', 2, TRUE, '가전'),
    ('일반가구', 'MID', '냉장고 렌탈 검토', 1, TRUE, '가전'),
    ('일반가구', 'MID', '세탁기 렌탈 검토', 2, TRUE, '가전'),
    ('일반가구', 'MID', '입주청소/생활서비스 비교', 3, FALSE, '생활');

//확인
SELECT *
FROM DIM_CHECKLIST_RULE
ORDER BY HOUSEHOLD_SEGMENT, BUDGET_TIER, PRIORITY;

//추천뷰
CREATE OR REPLACE VIEW VW_MOVING_RECOMMENDATION AS
SELECT
    S.REGION_ID,
    S.REGION_NAME,
    S.YEAR_MONTH,
    S.HOUSEHOLD_SEGMENT,
    S.BUDGET_TIER,
    C.ITEM_NAME,
    C.PRIORITY,
    C.IS_RENTAL_RELATED,
    C.ITEM_CATEGORY,
    T.RENTAL_MAIN_CATEGORY,
    T.RENTAL_SUB_CATEGORY,
    T.AVG_NET_SALES,
    T.AVG_POLICY_AMOUNT
FROM VW_REGION_HOUSEHOLD_SEGMENT S
LEFT JOIN DIM_CHECKLIST_RULE C
    ON S.HOUSEHOLD_SEGMENT = C.HOUSEHOLD_SEGMENT
   AND S.BUDGET_TIER = C.BUDGET_TIER
LEFT JOIN FACT_RENTAL_MARKET_TREND T
    ON S.REGION_ID = T.REGION_ID
   AND S.YEAR_MONTH = T.YEAR_MONTH;

//확인
SELECT *
FROM VW_MOVING_RECOMMENDATION
ORDER BY REGION_ID, YEAR_MONTH, PRIORITY
LIMIT 50;