USE DATABASE HACKATHON_DB;
USE SCHEMA HACKATHON_DM;

// llm 입력용 핵심 칼럼 뷰 생성
CREATE OR REPLACE VIEW VW_LLM_PROFILE_INPUT AS
SELECT
    REGION_ID,
    REGION_NAME,
    YEAR_MONTH,
    AVG_INCOME,
    AVG_HOUSEHOLD_INCOME,
    AVG_ASSET_AMOUNT,
    RATE_HIGHEND,
    AVG_MEME_PRICE_PER_SUPPLY_PYEONG,
    AVG_JEONSE_PRICE_PER_SUPPLY_PYEONG,
    AGE_UNDER5,
    FEMALE_20TO40,
    AGE_UNDER5_PER_FEMALE_20TO40,
    TOTAL_SALES,
    FOOD_SALES,
    HOME_LIFE_SERVICE_SALES,
    ELECTRONICS_FURNITURE_SALES,
    LARGE_DISCOUNT_STORE_SALES,
    SMALL_RETAIL_STORE_SALES,
    E_COMMERCE_SALES
FROM FACT_REGION_MONTH_PROFILE;

// 지역/월 기준으로 계약 수가 높은 렌탈 후보 뷰(미분류 제거)
CREATE OR REPLACE VIEW VW_LLM_RENTAL_CANDIDATES AS
SELECT
    REGION_ID,
    YEAR_MONTH,
    RENTAL_MAIN_CATEGORY,
    RENTAL_SUB_CATEGORY,
    CONTRACT_COUNT,
    AVG_NET_SALES,
    AVG_POLICY_AMOUNT,
    ROW_NUMBER() OVER (
        PARTITION BY REGION_ID, YEAR_MONTH
        ORDER BY CONTRACT_COUNT DESC, AVG_NET_SALES DESC
    ) AS RN
FROM FACT_RENTAL_MARKET_TREND
WHERE COALESCE(RENTAL_MAIN_CATEGORY, '') <> '미분류'
  AND COALESCE(RENTAL_MAIN_CATEGORY, '') <> ''
  AND COALESCE(RENTAL_SUB_CATEGORY, '') <> '미분류'
  AND COALESCE(RENTAL_SUB_CATEGORY, '') <> ''
  AND AVG_NET_SALES IS NOT NULL;

// 확인
SELECT *
FROM VW_LLM_RENTAL_CANDIDATES
WHERE REGION_ID = 1
ORDER BY YEAR_MONTH DESC, RN
LIMIT 20;

// 모델 목록 확인
CALL SNOWFLAKE.MODELS.CORTEX_BASE_MODELS_REFRESH();
SHOW MODELS IN SNOWFLAKE.MODELS;

// 모델 답변 테스트
SELECT AI_COMPLETE('claude-sonnet-4-5', '안녕. 한 줄로 자기소개해줘');

// 에러 메세지 확인
ALTER SESSION SET AI_SQL_ERROR_HANDLING_USE_FAIL_ON_ERROR = FALSE;

// 체크리스트 라벨 정규화 뷰 만들기
CREATE OR REPLACE VIEW VW_CHECKLIST_RULE_NORMALIZED AS
SELECT
    RULE_ID,
    HOUSEHOLD_SEGMENT AS SOURCE_HOUSEHOLD_SEGMENT,
    CASE
        WHEN HOUSEHOLD_SEGMENT = '육아가구' THEN '육아가구형'
        WHEN HOUSEHOLD_SEGMENT = '일반가구' THEN '일반가족형'
        WHEN HOUSEHOLD_SEGMENT = '프리미엄가구' THEN '일반가족형'
        WHEN HOUSEHOLD_SEGMENT = '가성비가구' THEN '1인가구형'
        ELSE '일반가족형'
    END AS HOUSEHOLD_TYPE,
    BUDGET_TIER,
    ITEM_NAME,
    PRIORITY,
    IS_RENTAL_RELATED,
    ITEM_CATEGORY
FROM DIM_CHECKLIST_RULE;

// 확인
SELECT *
FROM VW_CHECKLIST_RULE_NORMALIZED
ORDER BY HOUSEHOLD_TYPE, BUDGET_TIER, PRIORITY;

// 완전일치 후보만 뽑는 뷰 생성
CREATE OR REPLACE VIEW VW_CHECKLIST_RULE_STRICT AS
SELECT
    RULE_ID,
    HOUSEHOLD_TYPE,
    BUDGET_TIER,
    ITEM_NAME,
    PRIORITY,
    IS_RENTAL_RELATED,
    ITEM_CATEGORY
FROM VW_CHECKLIST_RULE_NORMALIZED;