USE DATABASE HACKATHON_DB;
USE SCHEMA HACKATHON_DM;

// llm 입력용 핵심 칼럼 뷰
CREATE OR REPLACE VIEW VW_LLM_PROFILE_INPUT AS
SELECT
    REGION_ID,
    REGION_NAME,
    YEAR_MONTH,
    AVG_INCOME,
    AVG_HOUSEHOLD_INCOME,
    AVG_ASSET_AMOUNT,
    RATE_HIGHEND,
    AVG_MEME_PRICE_PER_SUPPLY_PYEONG,
    AVG_JEONSE_PRICE_PER_SUPPLY_PYEONG,
    AGE_UNDER5,
    FEMALE_20TO40,
    AGE_UNDER5_PER_FEMALE_20TO40,
    TOTAL_SALES,
    FOOD_SALES,
    HOME_LIFE_SERVICE_SALES,
    ELECTRONICS_FURNITURE_SALES,
    LARGE_DISCOUNT_STORE_SALES,
    SMALL_RETAIL_STORE_SALES,
    E_COMMERCE_SALES
FROM FACT_REGION_MONTH_PROFILE;

// 기존 렌탈 후보 뷰
CREATE OR REPLACE VIEW VW_LLM_RENTAL_CANDIDATES AS
SELECT
    REGION_ID,
    YEAR_MONTH,
    RENTAL_MAIN_CATEGORY,
    RENTAL_SUB_CATEGORY,
    CONTRACT_COUNT,
    AVG_NET_SALES,
    AVG_POLICY_AMOUNT,
    ROW_NUMBER() OVER (
        PARTITION BY REGION_ID, YEAR_MONTH
        ORDER BY CONTRACT_COUNT DESC, AVG_NET_SALES DESC
    ) AS RN
FROM FACT_RENTAL_MARKET_TREND
WHERE COALESCE(RENTAL_MAIN_CATEGORY, '') <> '미분류'
  AND COALESCE(RENTAL_MAIN_CATEGORY, '') <> ''
  AND COALESCE(RENTAL_SUB_CATEGORY, '') <> '미분류'
  AND COALESCE(RENTAL_SUB_CATEGORY, '') <> ''
  AND AVG_NET_SALES IS NOT NULL;

// 최종 앱에서 사용하는 렌탈 점수화 베이스 뷰
CREATE OR REPLACE VIEW VW_RENTAL_RECOMMENDATION_SCORE AS
SELECT
    F.REGION_ID,
    D.REGION_NAME,
    F.YEAR_MONTH,
    F.RENTAL_MAIN_CATEGORY,
    F.RENTAL_SUB_CATEGORY,
    F.CONTRACT_COUNT,
    F.AVG_NET_SALES,
    F.AVG_POLICY_AMOUNT,

    CASE
        WHEN F.CONTRACT_COUNT >= 1000 THEN 40
        WHEN F.CONTRACT_COUNT >= 300 THEN 30
        WHEN F.CONTRACT_COUNT >= 100 THEN 20
        WHEN F.CONTRACT_COUNT >= 30 THEN 10
        ELSE 5
    END AS DEMAND_SCORE,

    CASE
        WHEN F.AVG_NET_SALES >= 400000 THEN 'HIGH'
        WHEN F.AVG_NET_SALES >= 250000 THEN 'MID'
        ELSE 'LOW'
    END AS PRICE_LEVEL
FROM FACT_RENTAL_MARKET_TREND F
LEFT JOIN DIM_REGION D
    ON F.REGION_ID = D.REGION_ID
WHERE COALESCE(F.RENTAL_MAIN_CATEGORY, '') <> '미분류'
  AND COALESCE(F.RENTAL_MAIN_CATEGORY, '') <> ''
  AND COALESCE(F.RENTAL_SUB_CATEGORY, '') <> '미분류'
  AND COALESCE(F.RENTAL_SUB_CATEGORY, '') <> ''
  AND F.AVG_NET_SALES IS NOT NULL;