USE DATABASE HACKATHON_DB;
USE SCHEMA HACKATHON_DM;

// 최근 6개월 지역 소비 패턴 추이
SELECT
    YEAR_MONTH,
    FOOD_SALES,
    HOME_LIFE_SERVICE_SALES,
    ELECTRONICS_FURNITURE_SALES,
    E_COMMERCE_SALES
FROM VW_LLM_PROFILE_INPUT
WHERE REGION_NAME = '{{REGION_NAME}}'
ORDER BY YEAR_MONTH DESC
LIMIT 6;

// 최근 6개월 상위 렌탈 카테고리 추이
WITH top_categories AS (
    SELECT RENTAL_SUB_CATEGORY
    FROM VW_RENTAL_RECOMMENDATION_SCORE
    WHERE REGION_NAME = '{{REGION_NAME}}'
      AND YEAR_MONTH = (
          SELECT MAX(YEAR_MONTH)
          FROM VW_RENTAL_RECOMMENDATION_SCORE
          WHERE REGION_NAME = '{{REGION_NAME}}'
      )
    ORDER BY CONTRACT_COUNT DESC
    LIMIT 3
)
SELECT
    YEAR_MONTH,
    RENTAL_SUB_CATEGORY,
    CONTRACT_COUNT,
    AVG_NET_SALES
FROM VW_RENTAL_RECOMMENDATION_SCORE
WHERE REGION_NAME = '{{REGION_NAME}}'
  AND RENTAL_SUB_CATEGORY IN (SELECT RENTAL_SUB_CATEGORY FROM top_categories)
ORDER BY YEAR_MONTH DESC, RENTAL_SUB_CATEGORY
LIMIT 18;