USE DATABASE ajd_subscription_contract_data;
SHOW SCHEMAS;
SHOW VIEWS IN SCHEMA ajd_subscription_contract_data.TELECOM_INSIGHTS;

//월별 지역 계약 뷰 확인
DESC VIEW ajd_subscription_contract_data.TELECOM_INSIGHTS.V01_MONTHLY_REGIONAL_CONTRACT_STATS;

SELECT *
FROM ajd_subscription_contract_data.TELECOM_INSIGHTS.V01_MONTHLY_REGIONAL_CONTRACT_STATS
LIMIT 10;

//지역별 신규 설치 뷰 확인
DESC VIEW ajd_subscription_contract_data.TELECOM_INSIGHTS.V05_REGIONAL_NEW_INSTALL;

SELECT *
FROM ajd_subscription_contract_data.TELECOM_INSIGHTS.V05_REGIONAL_NEW_INSTALL
LIMIT 10;

//렌탈가전 카테고리 트렌드 뷰 확인
DESC VIEW ajd_subscription_contract_data.TELECOM_INSIGHTS.V06_RENTAL_CATEGORY_TRENDS;

SELECT *
FROM ajd_subscription_contract_data.TELECOM_INSIGHTS.V06_RENTAL_CATEGORY_TRENDS
LIMIT 10;

//지역명확인
SELECT DISTINCT
    INSTALL_STATE,
    INSTALL_CITY
FROM AJD_SUBSCRIPTION_CONTRACT_DATA.TELECOM_INSIGHTS.V05_REGIONAL_NEW_INSTALL
WHERE INSTALL_STATE IN ('서울', '서울특별시')
ORDER BY 1, 2;

SELECT DISTINCT
    INSTALL_STATE,
    INSTALL_CITY
FROM AJD_SUBSCRIPTION_CONTRACT_DATA.TELECOM_INSIGHTS.V01_MONTHLY_REGIONAL_CONTRACT_STATS
WHERE INSTALL_STATE IN ('서울', '서울특별시')
ORDER BY 1, 2;