USE DATABASE richgo_population_apartment_data;
SHOW SCHEMAS;
SHOW TABLES IN SCHEMA richgo_population_apartment_data.HACKATHON_2025Q2;

//지역별 아파트 시세 테이블 구조 확인
DESC TABLE richgo_population_apartment_data.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H;

SELECT *
FROM richgo_population_apartment_data.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
LIMIT 10;

//20~40대 여성 + 5세 이하 영유아 관련 비율/규모 테이블 구조 확인
DESC TABLE richgo_population_apartment_data.HACKATHON_2025Q2.REGION_MOIS_POPULATION_AGE_UNDER5_PER_FEMALE_20TO40_M_H;

SELECT *
FROM richgo_population_apartment_data.HACKATHON_2025Q2.REGION_MOIS_POPULATION_AGE_UNDER5_PER_FEMALE_20TO40_M_H
LIMIT 10;


//지역명확인
SELECT DISTINCT
    SD,
    SGG
FROM RICHGO_POPULATION_APARTMENT_DATA.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H
WHERE SD IN ('서울', '서울특별시')
ORDER BY 1, 2;

SELECT DISTINCT
    SD,
    SGG
FROM RICHGO_POPULATION_APARTMENT_DATA.HACKATHON_2025Q2.REGION_MOIS_POPULATION_AGE_UNDER5_PER_FEMALE_20TO40_M_H
WHERE SD IN ('서울', '서울특별시')
ORDER BY 1, 2;
